# -*- coding: utf-8 -*-
"""Codingan 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FsZDaz2I2jsJewpe-UjAGGo682JeNdMA
"""

from sklearn.neighbors import NearestCentroid

# Database: Gerbang logika AND
# x = Data, Y = Target
x = [[0, 0], [1, 1], [1, 2], [2, 1], [2, 2], [3, 1], [3, 2], [4, 3], [5, 3], [5, 4]]
y = [0, 1, 3, 4, 5, 2, 1, 3, 4, 5]

# Training and Classify
clf = NearestCentroid()
clf. fit(x, y) 

# Prediksi
print ("Logika AND Metode K. Nearest Neighbors (KNN)") 
print ("Logika = Prediksi")
print ("0 0 = ", clf.predict([[0, 0]])) 
print ("1 1 = ", clf.predict([[1, 1]])) 
print ("1 2 = ", clf.predict([[1, 2]])) 
print ("2 1 = ", clf.predict([[2, 1]]))
print ("2 2 = ", clf.predict([[2, 2]]))
print ("3 1 = ", clf.predict([[3, 1]]))
print ("3 2 = ", clf.predict([[3, 2]]))
print ("4 3 = ", clf.predict([[4, 3]]))
print ("5 3 = ", clf.predict([[5, 3]]))
print ("5 4 = ", clf.predict([[5, 4]]))